# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('img', models.ImageField(default=None, upload_to=b'')),
                ('rent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_of_renters', models.IntegerField(default=1)),
                ('is_online', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='room.Case')),
                ('channels', models.TextField(default=None, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('simplex', models.TextField(default=None, null=True)),
                ('scheme', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Case'),
        ),
        migrations.AddField(
            model_name='group',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Case'),
        ),
    ]
