# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='simplex',
        ),
    ]
