# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='img_dir',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
