# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20160711_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='num_voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
