# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_case_img_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id',
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
