# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20160714_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
