# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20160607_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='img_dir',
        ),
        migrations.AddField(
            model_name='case',
            name='img',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
