# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20160607_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
