# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_group_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='num_voted',
        ),
    ]
