# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20160607_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='house_rent',
            field=models.IntegerField(default=0),
        ),
    ]
