# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_case_house_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='house_rent',
            new_name='rent',
        ),
    ]
