# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20160608_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='room',
            name='preference',
        ),
    ]
