# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 21:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='group_to_choice',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='allocation',
            name='room_to_price',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
