# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20160609_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='room.Case'),
        ),
    ]
