# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20160611_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='room.Case'),
        ),
    ]
